### ISSUE TITLE
Crash in SolidShield detection

### ISSUE THREAD

**Issue by SilasLaspada** [mnadareski/BurnOutSharp#64]
This file shouldn't contain SolidShield (but I'm not 100% sure). The crash is: 
```System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=BurnOutSharp
  StackTrace:
   at BurnOutSharp.ProtectionType.SolidShield.CheckContents(String file, Byte[] fileContent, Boolean includeDebug) in C:\Users\silas\Desktop\GIT\BurnOutSharp\BurnOutSharp\ProtectionType\SolidShield.cs:line 170
   at BurnOutSharp.FileType.Executable.<>c__DisplayClass3_0.<Scan>b__0(IContentCheck contentCheckClass) in C:\Users\silas\Desktop\GIT\BurnOutSharp\BurnOutSharp\FileType\Executable.cs:line 102
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
```

The file is "Quake4.exe" (SHA1: B718AE36887C74A8A44750CAD2C001EE62B02AF0)

**Comment by SilasLaspada** [comment]
Still present as of newest commit.
```System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=BurnOutSharp
  StackTrace:
   at BurnOutSharp.ProtectionType.SolidShield.CheckContents(String file, Byte[] fileContent, Boolean includeDebug) in C:\Users\silas\Desktop\GIT\BurnOutSharp\BurnOutSharp\ProtectionType\SolidShield.cs:line 123
   at BurnOutSharp.FileType.Executable.<>c__DisplayClass3_0.<Scan>b__0(IContentCheck contentCheckClass) in C:\Users\silas\Desktop\GIT\BurnOutSharp\BurnOutSharp\FileType\Executable.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
```

**Comment by SilasLaspada** [comment]
Fixed as of newest commit.
